# Calculate MCP counter TME cellularity on TCGAov samples

Script related to figure 3b

### Aim:
- Calculate MCP counter TME cellularity of TCGA OV samples

In [2]:
!python --version

Python 3.6.8 :: Anaconda custom (64-bit)

## Import packages

In [1]:
import pandas as pd

In [2]:
home = "~/git_repos/HGSOC_TME_Heterogeneity/"

## Load MCP counter results

In [4]:
mcp_results = home + 'Data/3/MCPcounterImmuneCells_TCGAov_Results.txt'

mcp_results = pd.read_csv(mcp_results,
                          sep='\t')

In [5]:
mcp_results.head()

,Term,TCGA.04.1348.01,TCGA.04.1357.01,TCGA.04.1362.01,TCGA.04.1364.01,TCGA.04.1365.01,TCGA.04.1514.01,TCGA.04.1519.01,TCGA.09.0364.01,TCGA.09.0366.01,...,TCGA.61.2102.01,TCGA.61.2104.01,TCGA.61.2109.01,TCGA.61.2110.01,TCGA.61.2111.01,TCGA.61.2113.01,TCGA.OY.A56P.01,TCGA.OY.A56Q.01,TCGA.VG.A8LO.01,TCGA.WR.A838.01
0,T cells,140.379514,284.691221,217.392593,41.826871,167.179664,80.249193,62.845686,55.527121,83.974364,...,33.929664,132.948129,149.716307,114.272093,151.906336,92.076529,49.997771,41.986000,97.385329,129.867629
1,CD8 T cells,82.011300,326.822900,5.295300,19.929100,66.295000,4.317800,1.780200,3.613600,27.747800,...,2.998800,20.933100,7.152100,2.382100,130.291200,34.594200,3.473100,3.332200,5.475500,0.384500
2,Cytotoxic lymphocytes,122.446500,289.747943,20.046643,1.877800,107.277386,11.226243,8.646457,2.968329,28.007686,...,11.138529,26.204414,47.407886,10.957600,31.050314,28.477571,12.022371,1.999329,7.638071,6.865486
3,NK cells,5.310562,10.823550,5.088475,4.187238,7.533512,1.619175,0.611938,1.580963,8.036325,...,2.024225,5.047013,5.006437,3.096700,3.938750,5.066825,1.936937,1.249575,3.985825,1.778163
4,B lineage,61.407637,220.784525,38.763562,98.479450,92.021987,155.476413,221.461962,90.735700,73.548650,...,162.011975,66.391712,209.316750,149.595050,89.462613,67.004463,11.721813,167.610787,74.160575,200.836225

### Add values per sample

In [6]:
mcp_TMEcell = mcp_results.sum(axis='index')

In [7]:
mcp_TMEcell.head()

Term               T cellsCD8 T cellsCytotoxic lymphocytesNK cell...
TCGA.04.1348.01                                               6952.4
TCGA.04.1357.01                                                12193
TCGA.04.1362.01                                              4465.01
TCGA.04.1364.01                                              3388.72
dtype: object

In [8]:
mcp_TMEcell_df = pd.DataFrame({'Term':mcp_TMEcell.index,
                               'MCP_TMEcellularity':mcp_TMEcell.values})

mcp_TMEcell_df = mcp_TMEcell_df.T

In [9]:
mcp_TMEcell_df

,0,1,2,3,4,5,6,7,8,9,...,298,299,300,301,302,303,304,305,306,307
Term,Term,TCGA.04.1348.01,TCGA.04.1357.01,TCGA.04.1362.01,TCGA.04.1364.01,TCGA.04.1365.01,TCGA.04.1514.01,TCGA.04.1519.01,TCGA.09.0364.01,TCGA.09.0366.01,...,TCGA.61.2102.01,TCGA.61.2104.01,TCGA.61.2109.01,TCGA.61.2110.01,TCGA.61.2111.01,TCGA.61.2113.01,TCGA.OY.A56P.01,TCGA.OY.A56Q.01,TCGA.VG.A8LO.01,TCGA.WR.A838.01
MCP_TMEcellularity,T cellsCD8 T cellsCytotoxic lymphocytesNK cell...,6952.4,12193,4465.01,3388.72,4937.83,14057.5,4037.18,8839.73,6099.79,...,32927.8,10420.7,6309.16,8200.98,6192.23,50960.5,7606.59,1629.01,8728.7,6448.61

In [14]:
del(mcp_TMEcell_df[0])

In [15]:
mcp_TMEcell_df

,1,2,3,4,5,6,7,8,9,10,...,298,299,300,301,302,303,304,305,306,307
Term,TCGA.04.1348.01,TCGA.04.1357.01,TCGA.04.1362.01,TCGA.04.1364.01,TCGA.04.1365.01,TCGA.04.1514.01,TCGA.04.1519.01,TCGA.09.0364.01,TCGA.09.0366.01,TCGA.09.0367.01,...,TCGA.61.2102.01,TCGA.61.2104.01,TCGA.61.2109.01,TCGA.61.2110.01,TCGA.61.2111.01,TCGA.61.2113.01,TCGA.OY.A56P.01,TCGA.OY.A56Q.01,TCGA.VG.A8LO.01,TCGA.WR.A838.01
MCP_TMEcellularity,6952.4,12193,4465.01,3388.72,4937.83,14057.5,4037.18,8839.73,6099.79,3091.51,...,32927.8,10420.7,6309.16,8200.98,6192.23,50960.5,7606.59,1629.01,8728.7,6448.61

#### Save file

In [16]:
mcp_TMEcell_df.to_csv('../../Data/3/MCPcounterTMEcellularity_TCGAov_Results.txt',
                      sep='\t',
                      header=False,
                      index=True)

# End script